TEMPLATE = app
CONFIG += console c++17 c11
CONFIG -= app_bundle
CONFIG -= qt

DEFINES += PX_PHYSX_STATIC_LIB

# options
# PX_SUPPORT_GPU_PHYSX
# PX_ENABLE_FEATURES_UNDER_CONSTRUCTION
# PX_PHYSX_STATIC_LIB [turns off a lot of DLL specific code]

# build style (do not define any for release code)
# PX_DEBUG    [optimisation off, SDK development asserts, very intrusive]
# PX_CHECKED  [code to detect invalid parameters, API race conditions, and other incorrect uses of the API]
# PX_PROFILE  [omits the checks, but still has PVD and memory instrumentation]

CONFIG(release, debug|release) {
}
CONFIG(debug, debug|release) {
    DEFINES += PX_CHECKED
}


INCLUDEPATH += \
    ../include \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/gjk \
    ../PhysX-105.1-physx-5.3.0/physx/source/fastxml/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/hf \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/api/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/include/pipeline \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/include/collision \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/include/utils \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxgpu/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/device \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/scenequery/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/ccd \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/File \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxmetadata/core/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/physxmetadata/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxmetadata/extensions/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Xml \
    ../PhysX-105.1-physx-5.3.0/physx/source/filebuf/include \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src

SOURCES += \
    SnippetHelloWorld.cpp \
    main.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src/CmCollection.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src/CmPtrTable.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src/CmRadixSort.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src/CmSerialize.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src/CmVisualization.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src/windows/CmWindowsDelayLoadHook.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/common/src/windows/CmWindowsModuleUpdateLoader.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/fastxml/src/PsFastXml.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/FdAllocator.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/FdAssert.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/FdFoundation.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/FdMathUtils.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/FdString.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/FdTempAllocator.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixAtomic.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixFPU.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixMutex.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixPrintString.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixSList.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixSocket.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixSync.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixThread.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/unix/FdUnixTime.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsAtomic.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsFPU.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsMutex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsPrintString.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsSList.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsSocket.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsSync.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsThread.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/foundation/windows/FdWindowsTime.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/ccd/GuCCDSweepConvexMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/ccd/GuCCDSweepPrimitives.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuAdjacencies.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuBarycentricCoordinates.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuEdgeList.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuMeshAnalysis.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuMeshCleaner.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuQuantizer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuSeparatingAxes.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/common/GuVertexReducer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactBoxBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactCapsuleBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactCapsuleCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactCapsuleConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactCapsuleMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactConvexConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactConvexMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactCustomGeometry.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactPlaneBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactPlaneCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactPlaneConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactPolygonPolygon.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactSphereBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactSphereCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactSphereMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactSpherePlane.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuContactSphereSphere.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/contact/GuFeatureCode.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex/GuBigConvexData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex/GuConvexHelper.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex/GuConvexMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex/GuConvexSupportTable.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex/GuConvexUtilsInternal.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex/GuHillClimbing.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/convex/GuShapeConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingBigConvexDataBuilder.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingBVH.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingConvexHullBuilder.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingConvexHullLib.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingConvexHullUtils.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingConvexMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingConvexMeshBuilder.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingConvexPolygonsBuilder.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingHF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingQuickHullConvexHullLib.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingTetrahedronMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingTriangleMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuCookingVolumeIntegration.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/cooking/GuRTreeCooking.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance/GuDistancePointBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance/GuDistancePointTetrahedron.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance/GuDistancePointTriangle.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance/GuDistanceSegmentBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance/GuDistanceSegmentSegment.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance/GuDistanceSegmentTriangle.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/distance/GuDistanceTriangleTriangle.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/gjk/GuEPA.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/gjk/GuGJKSimplex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/gjk/GuGJKTest.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuAABBPruner.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuAABBTree.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuAABBTreeUpdateMap.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuActorShapeMap.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuBounds.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuBucketPruner.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuBVH.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuCCTSweepTests.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuCookingSDF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuExtendedBucketPruner.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuFactory.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuGeometryQuery.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuGjkQuery.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuIncrementalAABBPruner.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuIncrementalAABBPrunerCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuIncrementalAABBTree.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuInternal.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuMaverickNode.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuMeshFactory.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuMetaData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuMTD.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuOverlapTests.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuPruningPool.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuQuerySystem.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuRaycastTests.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuSAH.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuSDF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuSecondaryPruner.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuSqInternal.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuSweepMTD.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuSweepSharedTests.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuSweepTests.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/GuWindingNumber.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/hf/GuHeightField.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/hf/GuHeightFieldUtil.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/hf/GuOverlapTestsHF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/hf/GuSweepsHF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionBoxBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionCapsuleTriangle.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionEdgeEdge.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionRayBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionRayCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionRaySphere.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionSphereBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionTetrahedronBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionTriangleBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/intersection/GuIntersectionTriangleTriangle.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV32.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV32Build.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4Build.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_AABBSweep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_BoxOverlap.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_CapsuleSweep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_CapsuleSweepAA.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_MeshMeshOverlap.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_OBBSweep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_Raycast.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_SphereOverlap.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuBV4_SphereSweep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuMeshQuery.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuMidphaseBV4.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuMidphaseRTree.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuOverlapTestsMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuRTree.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuRTreeQueries.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuSweepsMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuTetrahedronMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuTetrahedronMeshUtils.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuTriangleMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuTriangleMeshBV4.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/mesh/GuTriangleMeshRTree.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactBoxBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactBoxConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactCapsuleBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactCapsuleCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactCapsuleConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactCapsuleHeightField.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactCapsuleMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactConvexCommon.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactConvexConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactConvexHeightField.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactConvexMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactCustomGeometry.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactGenBoxConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactGenSphereCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactGenUtil.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactPlaneBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactPlaneCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactPlaneConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactSphereBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactSphereCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactSphereConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactSphereHeightField.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactSphereMesh.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactSpherePlane.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMContactSphereSphere.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMShapeConvex.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPCMTriangleContactGen.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/pcm/GuPersistentContactManifold.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepBoxBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepBoxSphere.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepBoxTriangle_FeatureBased.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepBoxTriangle_SAT.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepCapsuleBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepCapsuleCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepCapsuleTriangle.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepSphereCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepSphereSphere.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepSphereTriangle.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/geomutils/src/sweep/GuSweepTriangleUtils.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/immediatemode/src/NpImmediateMode.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/api/src/px_globals.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcContactCache.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcContactMethodImpl.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcMaterialMethodImpl.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcNpBatch.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcNpCacheStreamPair.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcNpContactPrepShared.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcNpMemBlockPool.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/common/src/pipeline/PxcNpThreadContext.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/src/PxsCCD.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/src/PxsContactManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/src/PxsContext.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/src/PxsDefaultMemoryManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/src/PxsIslandSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/src/PxsNphaseImplementationContext.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevel/software/src/PxsSimpleIslandManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpAABBManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpAABBManagerBase.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpBroadPhase.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpBroadPhaseABP.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpBroadPhaseMBP.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpBroadPhaseSap.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpBroadPhaseSapAux.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpBroadPhaseShared.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpBroadPhaseUpdate.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowlevelaabb/src/BpFiltering.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyArticulationContactPrep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyArticulationContactPrepPF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyConstraintPartition.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyConstraintSetup.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyConstraintSetupBlock.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyContactPrep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyContactPrep4.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyContactPrep4PF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyContactPrepPF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyDynamics.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyFeatherstoneArticulation.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyFeatherstoneForwardDynamic.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyFeatherstoneInverseDynamic.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyFrictionCorrelation.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyRigidBodyToSolverBody.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DySleep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DySolverConstraints.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DySolverConstraintsBlock.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DySolverControl.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DySolverControlPF.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DySolverPFConstraints.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DySolverPFConstraintsBlock.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyTGSContactPrep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyTGSContactPrepBlock.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyTGSDynamics.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyThreadContext.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/lowleveldynamics/src/DyThresholdTable.cpp \
#    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/device/linux/PhysXIndicatorLinux.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/device/windows/PhysXIndicatorWindows.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/gpu/PxGpu.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/gpu/PxPhysXGpuModuleLoader.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpActor.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpAggregate.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpArticulationJointReducedCoordinate.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpArticulationLink.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpArticulationReducedCoordinate.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpArticulationSensor.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpArticulationTendon.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpBounds.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpCheck.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpConstraint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpDebugViz.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpFactory.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpFEMCloth.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpFEMClothMaterial.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpFEMSoftBodyMaterial.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpFLIPMaterial.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpHairSystem.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpMaterial.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpMetaData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpMPMMaterial.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpParticleSystem.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpPBDMaterial.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpPhysics.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpPruningStructure.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpPvdSceneClient.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpPvdSceneQueryCollector.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpRigidDynamic.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpRigidStatic.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpScene.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpSceneFetchResults.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpSceneQueries.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpSerializerAdapter.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpShape.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpShapeManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/NpSoftBody.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/omnipvd/NpOmniPvd.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/omnipvd/NpOmniPvdRegistrationData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/omnipvd/OmniPvdChunkAlloc.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/omnipvd/OmniPvdPxSampler.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/PvdMetaDataPvdBinding.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/PvdPhysicsClient.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physx/src/windows/NpWindowsDelayLoadHook.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctBoxController.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctCapsuleController.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctCharacterController.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctCharacterControllerCallbacks.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctCharacterControllerManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctController.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctObstacleContext.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctSweptBox.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctSweptCapsule.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcharacterkinematic/src/CctSweptVolume.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcooking/src/Cooking.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxcooking/src/windows/WindowsCookingDelayLoadHook.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtBroadPhase.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtCollection.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtContactJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtConvexMeshExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtCpuWorkerThread.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtCustomGeometryExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtCustomSceneQuerySystem.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtD6Joint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtD6JointCreate.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtDefaultCpuDispatcher.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtDefaultErrorCallback.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtDefaultSimulationFilterShader.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtDefaultStreams.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtDistanceJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtExtensions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtFixedJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtGearJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtGjkQueryExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtMetaData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtParticleClothCooker.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtParticleExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtPrismaticJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtPvd.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtPxStringTable.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtRackAndPinionJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtRaycastCCD.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtRemeshingExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtRevoluteJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtRigidActorExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtRigidBodyExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSampling.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSceneQueryExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSceneQuerySystem.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSimpleFactory.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSmoothNormals.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSoftBodyExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSphericalJoint.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSqManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtSqQuery.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtTetMakerExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtTetrahedronMeshExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/ExtTriangleMeshExt.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/omnipvd/ExtOmniPvdRegistrationData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/omnipvd/OmniPvdPxExtensionsSampler.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnBinaryDeserialization.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnBinarySerialization.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnConvX.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnConvX_Align.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnConvX_Convert.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnConvX_Error.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnConvX_MetaData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnConvX_Output.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnConvX_Union.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Binary/SnSerializationContext.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/SnSerialization.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/SnSerializationRegistry.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/SnSerialUtils.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Xml/SnJointRepXSerializer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Xml/SnRepXCoreSerializer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Xml/SnRepXUpgrader.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/serialization/Xml/SnXmlSerialization.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtBVH.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtDelaunayBoundaryInserter.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtDelaunayTetrahedralizer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtFastWindingNumber.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtInsideTester.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtMeshSimplificator.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtOctreeTetrahedralizer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtRemesher.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtTetSplitting.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtTetUnionFind.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtUtilities.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxextensions/src/tet/ExtVoxelTetrahedralizer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxmetadata/core/src/PxAutoGeneratedMetaDataObjects.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxmetadata/core/src/PxMetaDataObjects.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxmetadata/extensions/src/PxExtensionAutoGeneratedMetaDataObjects.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/physxmetadata/src/PxVehicleAutoGeneratedMetaDataObjects.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/physxmetadata/src/PxVehicleMetaDataObjects.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleComponents.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleDrive.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleDrive4W.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleDriveNW.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleDriveTank.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleMetaData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleNoDrive.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleSDK.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleSerialization.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleSuspWheelTire4.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleTireFriction.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleUpdate.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/PxVehicleWheels.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/VehicleUtilControl.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/VehicleUtilSetup.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle/src/VehicleUtilTelemetry.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/commands/VhCommandHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/drivetrain/VhDrivetrainFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/drivetrain/VhDrivetrainHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/physxActor/VhPhysXActorFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/physxActor/VhPhysXActorHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/physxConstraints/VhPhysXConstraintFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/physxConstraints/VhPhysXConstraintHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/physxRoadGeometry/VhPhysXRoadGeometryFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/physxRoadGeometry/VhPhysXRoadGeometryHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/pvd/VhPvdFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/pvd/VhPvdHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/pvd/VhPvdWriter.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/rigidBody/VhRigidBodyFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/steering/VhSteeringFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/suspension/VhSuspensionFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/suspension/VhSuspensionHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/tire/VhTireFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/tire/VhTireHelpers.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/physxvehicle2/src/wheel/VhWheelFunctions.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxProfileEventImpl.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvd.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdDataStream.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdDefaultFileTransport.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdDefaultSocketTransport.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdImpl.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdMemClient.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdObjectModelMetaData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdObjectRegistrar.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdProfileZoneClient.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/pvd/src/PxPvdUserRenderer.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/scenequery/src/SqCompoundPruner.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/scenequery/src/SqCompoundPruningPool.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/scenequery/src/SqFactory.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/scenequery/src/SqManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/scenequery/src/SqQuery.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScActorCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScActorSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationJointCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationJointSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationSensorSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationTendonCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationTendonJointCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScArticulationTendonSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScBodyCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScBodySim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScBroadphase.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScCCD.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScConstraintBreakage.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScConstraintCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScConstraintInteraction.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScConstraintSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScElementInteractionMarker.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScElementSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScFEMClothCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScFEMClothShapeSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScFEMClothSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScFiltering.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScHairSystemCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScHairSystemShapeCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScHairSystemShapeSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScHairSystemSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScInteraction.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScIterators.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScKinematics.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScMetaData.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScNPhaseCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScParticleSystemCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScParticleSystemShapeCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScParticleSystemShapeSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScParticleSystemSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScPhysics.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScPipeline.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScRigidCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScRigidSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScScene.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScShapeCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScShapeInteraction.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScShapeSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScShapeSimBase.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScSimStats.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScSimulationController.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScSleep.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScSoftBodyCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScSoftBodyShapeSim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScSoftBodySim.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScSqBoundsManager.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScStaticCore.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScTriggerInteraction.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/simulationcontroller/src/ScVisualize.cpp \
    ../PhysX-105.1-physx-5.3.0/physx/source/task/src/TaskManager.cpp

HEADERS += \
    SnippetPVD.h \
    ../include/characterkinematic/PxBoxController.h \
    ../include/characterkinematic/PxCapsuleController.h \
    ../include/characterkinematic/PxController.h \
    ../include/characterkinematic/PxControllerBehavior.h \
    ../include/characterkinematic/PxControllerManager.h \
    ../include/characterkinematic/PxControllerObstacles.h \
    ../include/characterkinematic/PxExtended.h \
    ../include/collision/PxCollisionDefs.h \
    ../include/common/PxBase.h \
    ../include/common/PxCollection.h \
    ../include/common/PxCoreUtilityTypes.h \
    ../include/common/PxInsertionCallback.h \
    ../include/common/PxMetaData.h \
    ../include/common/PxMetaDataFlags.h \
    ../include/common/PxPhysXCommonConfig.h \
    ../include/common/PxProfileZone.h \
    ../include/common/PxRenderBuffer.h \
    ../include/common/PxRenderOutput.h \
    ../include/common/PxSerialFramework.h \
    ../include/common/PxSerializer.h \
    ../include/common/PxStringTable.h \
    ../include/common/PxTolerancesScale.h \
    ../include/common/PxTypeInfo.h \
    ../include/common/windows/PxWindowsDelayLoadHook.h \
    ../include/cooking/PxBVH33MidphaseDesc.h \
    ../include/cooking/PxBVH34MidphaseDesc.h \
    ../include/cooking/PxBVHDesc.h \
    ../include/cooking/Pxc.h \
    ../include/cooking/PxConvexMeshDesc.h \
    ../include/cooking/PxCooking.h \
    ../include/cooking/PxCookingInternal.h \
    ../include/cooking/PxMidphaseDesc.h \
    ../include/cooking/PxSDFDesc.h \
    ../include/cooking/PxTetrahedronMeshDesc.h \
    ../include/cooking/PxTriangleMeshDesc.h \
    ../include/cudamanager/PxCudaContext.h \
    ../include/cudamanager/PxCudaContextManager.h \
    ../include/cudamanager/PxCudaTypes.h \
    ../include/extensions/PxBinaryConverter.h \
    ../include/extensions/PxBroadPhaseExt.h \
    ../include/extensions/PxCollectionExt.h \
    ../include/extensions/PxConstraintExt.h \
    ../include/extensions/PxContactJoint.h \
    ../include/extensions/PxConvexMeshExt.h \
    ../include/extensions/PxCustomGeometryExt.h \
    ../include/extensions/PxCustomSceneQuerySystem.h \
    ../include/extensions/PxD6Joint.h \
    ../include/extensions/PxD6JointCreate.h \
    ../include/extensions/PxDefaultAllocator.h \
    ../include/extensions/PxDefaultCpuDispatcher.h \
    ../include/extensions/PxDefaultErrorCallback.h \
    ../include/extensions/PxDefaultSimulationFilterShader.h \
    ../include/extensions/PxDefaultStreams.h \
    ../include/extensions/PxDistanceJoint.h \
    ../include/extensions/PxExtensionsAPI.h \
    ../include/extensions/PxFixedJoint.h \
    ../include/extensions/PxGearJoint.h \
    ../include/extensions/PxGjkQueryExt.h \
    ../include/extensions/PxJoint.h \
    ../include/extensions/PxJointLimit.h \
    ../include/extensions/PxMassProperties.h \
    ../include/extensions/PxParticleClothCooker.h \
    ../include/extensions/PxParticleExt.h \
    ../include/extensions/PxPrismaticJoint.h \
    ../include/extensions/PxRackAndPinionJoint.h \
    ../include/extensions/PxRaycastCCD.h \
    ../include/extensions/PxRemeshingExt.h \
    ../include/extensions/PxRepXSerializer.h \
    ../include/extensions/PxRepXSimpleType.h \
    ../include/extensions/PxRevoluteJoint.h \
    ../include/extensions/PxRigidActorExt.h \
    ../include/extensions/PxRigidBodyExt.h \
    ../include/extensions/PxSamplingExt.h \
    ../include/extensions/PxSceneQueryExt.h \
    ../include/extensions/PxSceneQuerySystemExt.h \
    ../include/extensions/PxSerialization.h \
    ../include/extensions/PxShapeExt.h \
    ../include/extensions/PxSimpleFactory.h \
    ../include/extensions/PxSmoothNormals.h \
    ../include/extensions/PxSoftBodyExt.h \
    ../include/extensions/PxSphericalJoint.h \
    ../include/extensions/PxStringTableExt.h \
    ../include/extensions/PxTetMakerExt.h \
    ../include/extensions/PxTetrahedronMeshAnalysisResult.h \
    ../include/extensions/PxTetrahedronMeshExt.h \
    ../include/extensions/PxTriangleMeshAnalysisResult.h \
    ../include/extensions/PxTriangleMeshExt.h \
    ../include/filebuf/PxFileBuf.h \
    ../include/foundation/Px.h \
    ../include/foundation/PxAlignedMalloc.h \
    ../include/foundation/PxAlloca.h \
    ../include/foundation/PxAllocator.h \
    ../include/foundation/PxAllocatorCallback.h \
    ../include/foundation/PxAoS.h \
    ../include/foundation/PxArray.h \
    ../include/foundation/PxAssert.h \
    ../include/foundation/PxAtomic.h \
    ../include/foundation/PxBasicTemplates.h \
    ../include/foundation/PxBitAndData.h \
    ../include/foundation/PxBitMap.h \
    ../include/foundation/PxBitUtils.h \
    ../include/foundation/PxBounds3.h \
    ../include/foundation/PxBroadcast.h \
    ../include/foundation/PxErrorCallback.h \
    ../include/foundation/PxErrors.h \
    ../include/foundation/PxFlags.h \
    ../include/foundation/PxFoundation.h \
    ../include/foundation/PxFoundationConfig.h \
    ../include/foundation/PxFPU.h \
    ../include/foundation/PxHash.h \
    ../include/foundation/PxHashInternals.h \
    ../include/foundation/PxHashMap.h \
    ../include/foundation/PxHashSet.h \
    ../include/foundation/PxInlineAllocator.h \
    ../include/foundation/PxInlineAoS.h \
    ../include/foundation/PxInlineArray.h \
    ../include/foundation/PxIntrinsics.h \
    ../include/foundation/PxIO.h \
    ../include/foundation/PxMat33.h \
    ../include/foundation/PxMat34.h \
    ../include/foundation/PxMat44.h \
    ../include/foundation/PxMath.h \
    ../include/foundation/PxMathIntrinsics.h \
    ../include/foundation/PxMathUtils.h \
    ../include/foundation/PxMemory.h \
    ../include/foundation/PxMutex.h \
    ../include/foundation/PxPhysicsVersion.h \
    ../include/foundation/PxPinnedArray.h \
    ../include/foundation/PxPlane.h \
    ../include/foundation/PxPool.h \
    ../include/foundation/PxPreprocessor.h \
    ../include/foundation/PxProfiler.h \
    ../include/foundation/PxQuat.h \
    ../include/foundation/PxSIMDHelpers.h \
    ../include/foundation/PxSimpleTypes.h \
    ../include/foundation/PxSList.h \
    ../include/foundation/PxSocket.h \
    ../include/foundation/PxSort.h \
    ../include/foundation/PxSortInternals.h \
    ../include/foundation/PxStrideIterator.h \
    ../include/foundation/PxString.h \
    ../include/foundation/PxSync.h \
    ../include/foundation/PxTempAllocator.h \
    ../include/foundation/PxThread.h \
    ../include/foundation/PxTime.h \
    ../include/foundation/PxTransform.h \
    ../include/foundation/PxUnionCast.h \
    ../include/foundation/PxUserAllocated.h \
    ../include/foundation/PxUtilities.h \
    ../include/foundation/PxVec2.h \
    ../include/foundation/PxVec3.h \
    ../include/foundation/PxVec4.h \
    ../include/foundation/PxVecMath.h \
    ../include/foundation/PxVecMathAoSScalar.h \
    ../include/foundation/PxVecMathAoSScalarInline.h \
    ../include/foundation/PxVecMathSSE.h \
    ../include/foundation/PxVecQuat.h \
    ../include/foundation/PxVecTransform.h \
    ../include/foundation/unix/neon/PxUnixNeonAoS.h \
    ../include/foundation/unix/neon/PxUnixNeonInlineAoS.h \
    ../include/foundation/unix/PxUnixAoS.h \
    ../include/foundation/unix/PxUnixFPU.h \
    ../include/foundation/unix/PxUnixInlineAoS.h \
    ../include/foundation/unix/PxUnixIntrinsics.h \
    ../include/foundation/unix/PxUnixMathIntrinsics.h \
    ../include/foundation/unix/PxUnixTrigConstants.h \
    ../include/foundation/unix/sse2/PxUnixSse2AoS.h \
    ../include/foundation/unix/sse2/PxUnixSse2InlineAoS.h \
    ../include/foundation/windows/PxWindowsAoS.h \
    ../include/foundation/windows/PxWindowsFPU.h \
    ../include/foundation/windows/PxWindowsInclude.h \
    ../include/foundation/windows/PxWindowsInlineAoS.h \
    ../include/foundation/windows/PxWindowsIntrinsics.h \
    ../include/foundation/windows/PxWindowsMathIntrinsics.h \
    ../include/foundation/windows/PxWindowsTrigConstants.h \
    ../include/geometry/PxBoxGeometry.h \
    ../include/geometry/PxBVH.h \
    ../include/geometry/PxBVHBuildStrategy.h \
    ../include/geometry/PxCapsuleGeometry.h \
    ../include/geometry/PxConvexMesh.h \
    ../include/geometry/PxConvexMeshGeometry.h \
    ../include/geometry/PxCustomGeometry.h \
    ../include/geometry/PxGeometry.h \
    ../include/geometry/PxGeometryHelpers.h \
    ../include/geometry/PxGeometryHit.h \
    ../include/geometry/PxGeometryInternal.h \
    ../include/geometry/PxGeometryQuery.h \
    ../include/geometry/PxGeometryQueryContext.h \
    ../include/geometry/PxGeometryQueryFlags.h \
    ../include/geometry/PxGjkQuery.h \
    ../include/geometry/PxHairSystemDesc.h \
    ../include/geometry/PxHairSystemGeometry.h \
    ../include/geometry/PxHeightField.h \
    ../include/geometry/PxHeightFieldDesc.h \
    ../include/geometry/PxHeightFieldFlag.h \
    ../include/geometry/PxHeightFieldGeometry.h \
    ../include/geometry/PxHeightFieldSample.h \
    ../include/geometry/PxMeshQuery.h \
    ../include/geometry/PxMeshScale.h \
    ../include/geometry/PxParticleSystemGeometry.h \
    ../include/geometry/PxPlaneGeometry.h \
    ../include/geometry/PxReportCallback.h \
    ../include/geometry/PxSimpleTriangleMesh.h \
    ../include/geometry/PxSphereGeometry.h \
    ../include/geometry/PxTetrahedron.h \
    ../include/geometry/PxTetrahedronMesh.h \
    ../include/geometry/PxTetrahedronMeshGeometry.h \
    ../include/geometry/PxTriangle.h \
    ../include/geometry/PxTriangleMesh.h \
    ../include/geometry/PxTriangleMeshGeometry.h \
    ../include/geomutils/PxContactBuffer.h \
    ../include/geomutils/PxContactPoint.h \
    ../include/gpu/PxGpu.h \
    ../include/gpu/PxPhysicsGpu.h \
    ../include/omnipvd/PxOmniPvd.h \
    ../include/pvd/PxPvd.h \
    ../include/pvd/PxPvdSceneClient.h \
    ../include/pvd/PxPvdTransport.h \
    ../include/PxActor.h \
    ../include/PxActorData.h \
    ../include/PxAggregate.h \
    ../include/PxAnisotropy.h \
    ../include/PxArrayConverter.h \
    ../include/PxArticulationFlag.h \
    ../include/PxArticulationJointReducedCoordinate.h \
    ../include/PxArticulationLink.h \
    ../include/PxArticulationReducedCoordinate.h \
    ../include/PxArticulationTendon.h \
    ../include/PxArticulationTendonData.h \
    ../include/PxAttachment.h \
    ../include/PxBaseMaterial.h \
    ../include/PxBroadPhase.h \
    ../include/PxClient.h \
    ../include/PxConeLimitedConstraint.h \
    ../include/PxConstraint.h \
    ../include/PxConstraintDesc.h \
    ../include/PxContact.h \
    ../include/PxContactModifyCallback.h \
    ../include/PxDeletionListener.h \
    ../include/PxFEMClothFlags.h \
    ../include/PxFEMClothMaterial.h \
    ../include/PxFEMMaterial.h \
    ../include/PxFEMParameter.h \
    ../include/PxFEMSoftBodyMaterial.h \
    ../include/PxFiltering.h \
    ../include/PxFLIPMaterial.h \
    ../include/PxForceMode.h \
    ../include/PxHairSystemFlag.h \
    ../include/PxImmediateMode.h \
    ../include/PxIsosurfaceExtraction.h \
    ../include/PxLineStripSkinning.h \
    ../include/PxLockedData.h \
    ../include/PxMaterial.h \
    ../include/PxMPMMaterial.h \
    ../include/PxNodeIndex.h \
    ../include/PxParticleBuffer.h \
    ../include/PxParticleGpu.h \
    ../include/PxParticleMaterial.h \
    ../include/PxParticleNeighborhoodProvider.h \
    ../include/PxParticleSolverType.h \
    ../include/PxParticleSystem.h \
    ../include/PxParticleSystemFlag.h \
    ../include/PxPBDMaterial.h \
    ../include/PxPBDParticleSystem.h \
    ../include/PxPhysics.h \
    ../include/PxPhysicsAPI.h \
    ../include/PxPhysicsSerialization.h \
    ../include/PxPhysXConfig.h \
    ../include/PxPruningStructure.h \
    ../include/PxQueryFiltering.h \
    ../include/PxQueryReport.h \
    ../include/PxRigidActor.h \
    ../include/PxRigidBody.h \
    ../include/PxRigidDynamic.h \
    ../include/PxRigidStatic.h \
    ../include/PxScene.h \
    ../include/PxSceneDesc.h \
    ../include/PxSceneLock.h \
    ../include/PxSceneQueryDesc.h \
    ../include/PxSceneQuerySystem.h \
    ../include/PxSDFBuilder.h \
    ../include/PxShape.h \
    ../include/PxSimulationEventCallback.h \
    ../include/PxSimulationStatistics.h \
    ../include/PxSmoothing.h \
    ../include/PxSoftBody.h \
    ../include/PxSoftBodyFlag.h \
    ../include/PxSparseGridParams.h \
    ../include/PxVisualizationParameter.h \
    ../include/solver/PxSolverDefs.h \
    ../include/task/PxCpuDispatcher.h \
    ../include/task/PxTask.h \
    ../include/task/PxTaskManager.h \
    ../include/vehicle/PxVehicleComponents.h \
    ../include/vehicle/PxVehicleDrive.h \
    ../include/vehicle/PxVehicleDrive4W.h \
    ../include/vehicle/PxVehicleDriveNW.h \
    ../include/vehicle/PxVehicleDriveTank.h \
    ../include/vehicle/PxVehicleNoDrive.h \
    ../include/vehicle/PxVehicleSDK.h \
    ../include/vehicle/PxVehicleShaders.h \
    ../include/vehicle/PxVehicleTireFriction.h \
    ../include/vehicle/PxVehicleUpdate.h \
    ../include/vehicle/PxVehicleUtil.h \
    ../include/vehicle/PxVehicleUtilControl.h \
    ../include/vehicle/PxVehicleUtilSetup.h \
    ../include/vehicle/PxVehicleUtilTelemetry.h \
    ../include/vehicle/PxVehicleWheels.h \
    ../include/vehicle2/braking/PxVehicleBrakingFunctions.h \
    ../include/vehicle2/braking/PxVehicleBrakingParams.h \
    ../include/vehicle2/commands/PxVehicleCommandHelpers.h \
    ../include/vehicle2/commands/PxVehicleCommandParams.h \
    ../include/vehicle2/commands/PxVehicleCommandStates.h \
    ../include/vehicle2/drivetrain/PxVehicleDrivetrainComponents.h \
    ../include/vehicle2/drivetrain/PxVehicleDrivetrainFunctions.h \
    ../include/vehicle2/drivetrain/PxVehicleDrivetrainHelpers.h \
    ../include/vehicle2/drivetrain/PxVehicleDrivetrainParams.h \
    ../include/vehicle2/drivetrain/PxVehicleDrivetrainStates.h \
    ../include/vehicle2/physxActor/PxVehiclePhysXActorComponents.h \
    ../include/vehicle2/physxActor/PxVehiclePhysXActorFunctions.h \
    ../include/vehicle2/physxActor/PxVehiclePhysXActorHelpers.h \
    ../include/vehicle2/physxActor/PxVehiclePhysXActorStates.h \
    ../include/vehicle2/physxConstraints/PxVehiclePhysXConstraintComponents.h \
    ../include/vehicle2/physxConstraints/PxVehiclePhysXConstraintFunctions.h \
    ../include/vehicle2/physxConstraints/PxVehiclePhysXConstraintHelpers.h \
    ../include/vehicle2/physxConstraints/PxVehiclePhysXConstraintParams.h \
    ../include/vehicle2/physxConstraints/PxVehiclePhysXConstraintStates.h \
    ../include/vehicle2/physxRoadGeometry/PxVehiclePhysXRoadGeometryComponents.h \
    ../include/vehicle2/physxRoadGeometry/PxVehiclePhysXRoadGeometryFunctions.h \
    ../include/vehicle2/physxRoadGeometry/PxVehiclePhysXRoadGeometryHelpers.h \
    ../include/vehicle2/physxRoadGeometry/PxVehiclePhysXRoadGeometryParams.h \
    ../include/vehicle2/physxRoadGeometry/PxVehiclePhysXRoadGeometryState.h \
    ../include/vehicle2/pvd/PxVehiclePvdComponents.h \
    ../include/vehicle2/pvd/PxVehiclePvdFunctions.h \
    ../include/vehicle2/pvd/PxVehiclePvdHelpers.h \
    ../include/vehicle2/PxVehicleAPI.h \
    ../include/vehicle2/PxVehicleComponent.h \
    ../include/vehicle2/PxVehicleComponentSequence.h \
    ../include/vehicle2/PxVehicleFunctions.h \
    ../include/vehicle2/PxVehicleLimits.h \
    ../include/vehicle2/PxVehicleMaths.h \
    ../include/vehicle2/PxVehicleParams.h \
    ../include/vehicle2/rigidBody/PxVehicleRigidBodyComponents.h \
    ../include/vehicle2/rigidBody/PxVehicleRigidBodyFunctions.h \
    ../include/vehicle2/rigidBody/PxVehicleRigidBodyParams.h \
    ../include/vehicle2/rigidBody/PxVehicleRigidBodyStates.h \
    ../include/vehicle2/roadGeometry/PxVehicleRoadGeometryState.h \
    ../include/vehicle2/steering/PxVehicleSteeringFunctions.h \
    ../include/vehicle2/steering/PxVehicleSteeringParams.h \
    ../include/vehicle2/suspension/PxVehicleSuspensionComponents.h \
    ../include/vehicle2/suspension/PxVehicleSuspensionFunctions.h \
    ../include/vehicle2/suspension/PxVehicleSuspensionHelpers.h \
    ../include/vehicle2/suspension/PxVehicleSuspensionParams.h \
    ../include/vehicle2/suspension/PxVehicleSuspensionStates.h \
    ../include/vehicle2/tire/PxVehicleTireComponents.h \
    ../include/vehicle2/tire/PxVehicleTireFunctions.h \
    ../include/vehicle2/tire/PxVehicleTireHelpers.h \
    ../include/vehicle2/tire/PxVehicleTireParams.h \
    ../include/vehicle2/tire/PxVehicleTireStates.h \
    ../include/vehicle2/wheel/PxVehicleWheelComponents.h \
    ../include/vehicle2/wheel/PxVehicleWheelFunctions.h \
    ../include/vehicle2/wheel/PxVehicleWheelHelpers.h \
    ../include/vehicle2/wheel/PxVehicleWheelParams.h \
    ../include/vehicle2/wheel/PxVehicleWheelStates.h

